---
title: "Group_9_Analysis"
author: "Brent Strong, Enyu Li, Haotian Wang, Honjin Ren, Mu He"
date: "3/7/2022"
output: pdf_document
---

#Loading of libraries and data import

```{r libraries, echo = FALSE}

#Load necessary libraries for the data exploration and analysis.

library(tidyverse)
library(moderndive)
library(skimr)
library(kableExtra)
library(gridExtra)
library(broom)
library(olsrr)
library(gapminder)
library(sjPlot)
library(stats)
library(jtools)
library(MASS)
library(janitor)
library(ggplot2)
library(caret)
library(lme4)
```

```{r import, echo = FALSE}

#Read in data from github and abbreviate certain country names.

analysis <- read_csv("https://raw.githubusercontent.com/brent-strong/DAS2022-Group-09/main/dataset9.csv")
glimpse(analysis)

for(i in 1:nrow(analysis)){
  if(str_detect(analysis$country_of_origin[i], "Puerto Rico")){
    analysis$country_of_origin[i] <- "Puerto Rico"
  }
  if(str_detect(analysis$country_of_origin[i], "Hawaii")){
    analysis$country_of_origin[i] <- "Hawaii"
  }
  if(str_detect(analysis$country_of_origin[i], "Tanzania")){
    analysis$country_of_origin[i] <- "Tanzania"
  }
  else{
    analysis$country_of_origin[i] <- analysis$country_of_origin[i]
  }
}
# View(analysis)
```

#Exploratory analysis

```{r import, echo = FALSE}

# glimpse(analysis)

#Use the skim function but separate out altitude_mean_meters and harvested in order to make the tables easier to read.

analysis %>%
  select(-altitude_mean_meters, -harvested) %>%
  skim_without_charts()

analysis %>%
  select(altitude_mean_meters, harvested) %>%
  skim_without_charts()

#Examine the proportion of batches that are good:

mean(analysis$Qualityclass=="Good")
```

```{r aroma, echo = FALSE}

# glimpse(analysis)

#Generate histogram to visualize aroma data.

ggplot(data = analysis, mapping = aes(x = aroma)) +
  geom_histogram()

#Generate boxplot to visualize aroma data.

ggplot(data = analysis, mapping = aes(y = aroma)) +
  geom_boxplot()

#Single observation with a value of 0 is odd. 

```

```{r flavor, echo = FALSE}

# glimpse(analysis)

#Generate histogram to visualize flavor data.

ggplot(data = analysis, mapping = aes(x = flavor)) +
  geom_histogram()

#Generate boxplot to visualize flavor data.

ggplot(data = analysis, mapping = aes(y = flavor)) +
  geom_boxplot()

# Single observation with a value of 0 is odd. 

```

```{r acidity, echo = FALSE}

# glimpse(analysis)

# Generate histogram to visualize acidity data.

ggplot(data = analysis, mapping = aes(x = acidity)) +
  geom_histogram()

# Generate boxplot to visualize acidity data.

ggplot(data = analysis, mapping = aes(y = acidity)) +
  geom_boxplot()

# Single observation with a value of 0 is odd. See if this same observation has a value of 0 for flavor and aroma as well. 

analysis %>% 
  filter(acidity == 0 & flavor == 0 & aroma == 0)

#Will delete the observation in the formal analysis. 

```

```{r category_two_defects, echo = FALSE}

# glimpse(analysis)

# Generate histogram to visualize category_two_defects data.

ggplot(data = analysis, mapping = aes(x = category_two_defects)) +
  geom_histogram()

# Generate boxplot to visualize category_two_defects data.

ggplot(data = analysis, mapping = aes(y = category_two_defects)) +
  geom_boxplot()

# Apply log(x+1) transformation and then visualize the data set.

analysis1 <- analysis %>%
  mutate(defects_log = log(category_two_defects+1))
 
# Generate histogram to visualize category_two_defects data after log-transformation.

ggplot(data = analysis1, mapping = aes(x = defects_log)) +
  geom_histogram()

# Generate boxplot to visualize category_two_defects data after log-transformation.

ggplot(data = analysis1, mapping = aes(y = defects_log)) +
  geom_boxplot()

```

```{r altitude, echo = FALSE}

# glimpse(analysis)

# Generate histogram to visualize altitude data.

ggplot(data = analysis, mapping = aes(x = altitude_mean_meters)) +
  geom_histogram()

# Generate boxplot to visualize altitude data.

ggplot(data = analysis, mapping = aes(y = altitude_mean_meters)) +
  geom_boxplot()

# Mt. Everest is only 8,849 meters tall. Remove any observations with altitudes higher than that.

analysis2 <- analysis %>%
  filter(altitude_mean_meters < 8849)

# Generate histogram to visualize altitude data after removing implausuble observations.

ggplot(data = analysis2, mapping = aes(x = altitude_mean_meters)) +
  geom_histogram()

# Generate boxplot to visualize altitude data after removing implausible observations.

ggplot(data = analysis2, mapping = aes(y = altitude_mean_meters)) +
  geom_boxplot()
  
```

```{r harvested, echo = FALSE}

# glimpse(analysis)

# Generate histogram to visualize year of harvest (harvested) data.

ggplot(data = analysis, mapping = aes(x = harvested)) +
  geom_histogram()

# Generate boxplot to visualize year of harvest (harvested) data.

ggplot(data = analysis, mapping = aes(y = harvested)) +
  geom_boxplot()

```

```{r country, echo = FALSE}

# glimpse(analysis)

# Create a new data set with the proportion of batches that were good and the number of observations.  

analysis3 <- analysis %>%
  mutate(Qualityclass_indicator = 0 + as.numeric(Qualityclass=="Good")) %>%
  group_by(country_of_origin) %>%
  summarize(proportion = mean(Qualityclass_indicator), n=n()) %>%
  arrange(desc(proportion))

# View(analysis3)

#Create a bar chart to visualize the proportion of batches that were good for each country. Split up the visualizations into four groups. 

p1<-ggplot(data = analysis3[1:9,], mapping = aes(x = country_of_origin, y = proportion)) +
  geom_col() + geom_text(data = analysis3[1:9,], aes(label = n), nudge_y=0.25)

p2<-ggplot(data = analysis3[10:18,], mapping = aes(x = country_of_origin, y = proportion)) +
  geom_col() + geom_text(data = analysis3[10:18,], aes(label = n), nudge_y=0.35)

p3<-ggplot(data = analysis3[19:26,], mapping = aes(x = country_of_origin, y = proportion)) +
  geom_col() + geom_text(data = analysis3[19:26,], aes(label = n), nudge_y=0.35)

p4<-ggplot(data = analysis3[27:34,], mapping = aes(x = country_of_origin, y = proportion)) +
  geom_col() + geom_text(data = analysis3[27:34,], aes(label = n), nudge_y=0.3)

grid.arrange(p1, p2, p3, p4, nrow = 4)
```

#Creation of the final data set

```{r data, echo = FALSE}

# glimpse(analysis)

# Create the final data set. Remove observations that have implausible values for at least one of the variables. Standardize aroma, flavor, acidity, and altitude. Apply a log(x+1) transformation to category_two_defects variable. Turn Qualityclass into an indicator variable so that it can be used in the logistic regression analysis. Remove unneeded variables.

coffee_final <- analysis %>%
  filter(acidity != 0 & (altitude_mean_meters < 8849 | is.na(altitude_mean_meters))) %>%
  mutate(aroma = scale(aroma), flavor=scale(flavor), acidity=scale(acidity), defects_log = log(category_two_defects + 1), year = as.factor(harvested), Qualityclass = 0 + as.numeric(Qualityclass == "Good")) 

#Divide into 3 levels for altitude based on information obtained in literature review.

coffee_final$altitude_level_1 <- ifelse(coffee_final$altitude_mean_meters<900,1,0)
coffee_final$altitude_level_2 <- ifelse(coffee_final$altitude_mean_meters>=900 & coffee_final$altitude_mean_meters<=1200,1,0)
coffee_final$altitude_level_3 <- ifelse(coffee_final$altitude_mean_meters>1200,1,0)
coffee_final <- coffee_final %>%
  mutate(altitude_level = as.character(altitude_level_1 + altitude_level_2*2 + altitude_level_3*3))
  
# Finally we can get the final dataset coffee_final

coffee_final <- coffee_final %>%
  dplyr::select(country_of_origin, aroma, flavor, acidity, defects_log, year, altitude_level, Qualityclass)
  
# View the final data set and make sure that the standardizations and transformation were appropriately applied.

skim_without_charts(coffee_final)
glimpse(coffee_final)

```

# Formal Analysis

```{r}

#Fit a logistic regression model with no intercept to examine the association of each altitude level with the probability of a particular batch having a good quality rating. 

model_altitude_level <- glm(Qualityclass ~ altitude_level - 1, data = coffee_final,family = binomial(link = "logit"))
summary(model_altitude_level)
```


```{r}

#Fit a logistic regression model  to examine the association of each year with the probability of a particular batch having a good quality rating. 

model_year <- glm(Qualityclass ~ year, data = coffee_final,family = binomial(link = "logit"))
summary(model_year)
```


```{r}

#Fit a logistic regression model with each country as an indicator variable.

model_country <- glm(Qualityclass ~ country_of_origin, data = coffee_final,family = binomial(link = "logit"))
summary(model_country)
```


```{r}

#Create indicator variables for countries that appear to have a  highly significant influence on coffee quality. 

coffee_final$Colombia <- ifelse(coffee_final$country_of_origin == 'Colombia',1,0)
coffee_final$Mexico <- ifelse(coffee_final$country_of_origin == 'Mexico',1,0)
coffee_final$Honduras <- ifelse(coffee_final$country_of_origin == 'Honduras',1,0)
coffee_final$Kenya <- ifelse(coffee_final$country_of_origin == 'Kenya',1,0)
#glimpse(coffee_final)
```

```{r}

#Fit model with just these indicator variables. 

model_co_4 <- glm(Qualityclass ~ Colombia + Mexico + Honduras + Kenya-1, data = coffee_final,family = binomial(link = "logit"))
summary(model_co_4)
```


```{r}

#Fit logistic regression model including every possible predictor. Fitted probabilites of 0 or 1 occurred indicating the need for a simpler model.

model_all <- glm(Qualityclass ~ aroma + flavor + acidity + country_of_origin + defects_log + altitude_level + year, data = coffee_final,family = binomial(link = "logit"))
summary(model_all)
```

```{r}

#Fit logistic regression model with only indicator variables for influential countries retained. Use a data set with observations that having any missing values removed (i.e., complete observations).

coffee_final_nomiss <- coffee_final %>%
  filter(!is.na(altitude_level)&!is.na(year))
glimpse(coffee_final_nomiss)

model_all_2 <- glm(Qualityclass ~ aroma + flavor + acidity + Colombia + Mexico + Honduras + Kenya + defects_log + altitude_level + year, data = coffee_final_nomiss, family = binomial(link = "logit"))
summary(model_all_2)
```

```{r}

#Perform stepwise selection by minimizing the AIC value to get the best model. Use only complete observations.

stepAIC(model_all_2, direction = 'both')
```

```{r}

#Fit logistic regression model with only indicator variables for influential countries retained. Use a data set with missing observations filled in with year and altitude imputed to the most common category.

table(coffee_final$year)
table(coffee_final$altitude_level)

coffee_final_imputed <- coffee_final %>%
  mutate(altitude_level=as.factor(ifelse(is.na(altitude_level),3,altitude_level)), year=as.factor(ifelse(is.na(year),3,year)))

table(coffee_final_imputed$year)
table(coffee_final_imputed$altitude_level)

model_all_3 <- glm(Qualityclass ~ aroma + flavor + acidity + Colombia + Mexico + Honduras + Kenya + defects_log + altitude_level + year, data = coffee_final_imputed, family = binomial(link = "logit"))
summary(model_all_3)

```

```{r}

#Perform stepwise selection by minimizing the AIC value to get the best model. Use imputed data set.

stepAIC(model_all_3, direction = 'both')
```

```{r}

#Fit the best logistic regression model (same one was found using both approaches) to all available data. Missingness is not an issue because altitude and year are dropped. 

model_best <- glm(Qualityclass ~ aroma + flavor + acidity + Colombia + Mexico + defects_log, data = coffee_final,family = binomial(link = "logit"))
summary(model_best)
```

```{r}

#Use 10-fold cross-validation to assess the predictive performance of the model. 

set.seed(50)
folds <- createFolds(y=coffee_final$Qualityclass, k=10)
accuracy <- as.numeric()
for(i in 1:10){
  fold_test <- coffee_final[folds[[i]],]
  fold_train <- coffee_final[-folds[[i]],]
  fold_pre <- glm(Qualityclass ~ aroma + flavor + acidity + Colombia + Mexico + defects_log,family = binomial(link = logit), data =fold_train )
  fold_predict <- predict(fold_pre,type='response',newdata=fold_test)
  fold_predict <- ifelse(fold_predict >= 0.5, 1, 0)
  accuracy[i] <- mean(fold_predict == fold_test[,8])
}
mean(accuracy)
```

```{r}

#Fit a generalized linear mixed model with a random intercept for country as a sensitivity analysis. 

model_glmm <- glmer(Qualityclass ~ 1 + aroma + flavor + acidity + defects_log + (1|country_of_origin), data = coffee_final,family = binomial(link = "logit"))
summary(model_glmm, corr=FALSE)
```

```{r}

#Use 10-fold cross-validation to assess the predictive performance of the model when country indicators are not included. 

set.seed(50)
folds <- createFolds(y=coffee_final$Qualityclass, k=10)
accuracy <- as.numeric()
for(i in 1:10){
  fold_test <- coffee_final[folds[[i]],]
  fold_train <- coffee_final[-folds[[i]],]
  fold_pre <- glm(Qualityclass ~ aroma + flavor + acidity + defects_log,family = binomial(link = logit), data =fold_train)
  fold_predict <- predict(fold_pre,type='response',newdata=fold_test)
  fold_predict <- ifelse(fold_predict >= 0.5, 1, 0)
  accuracy[i] <- mean(fold_predict == fold_test[,8])
}
mean(accuracy)
```


